import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage debe usarse dentro de LanguageProvider');
  }
  return context;
};

// Traducciones completas - SIN CLAVES DUPLICADAS
const translations = {
  es: {
    // ===== GENERAL =====
    'inicio': 'Inicio',
    'tienda': 'Tienda',
    'servicios': 'Servicios',
    'carrito': 'Carrito',
    'perfil': 'Perfil',
    'buscar': 'Buscar',
    'ingresar': 'Ingresar',
    'cerrar_sesion': 'Cerrar sesión',
    'mi_cuenta': 'Mi cuenta',
    'admin': 'Admin',
    'panel_admin': 'Panel Admin',
    'volver': 'Volver',
    'atras': 'Atrás',
    'cancelar': 'Cancelar',
    'guardar': 'Guardar',
    'aceptar': 'Aceptar',
    'cargando': 'Cargando...',
    'error': 'Error',
    'exito': 'Éxito',
    'volver_inicio': 'Volver al inicio',
    'procesando_general': 'Procesando...',
    'confirmar_eliminacion': '¿Estás seguro de eliminar este elemento?',
    'cambios_guardados': 'Cambios guardados correctamente',
    'sin_datos': 'No hay datos para mostrar',
    
    // ===== HEADER =====
    'buscar_productos': 'Buscar productos, marcas y más...',
    'explorar_tienda': 'Explorar Tienda',
    'nuestros_servicios': 'Nuestros Servicios',
    
    // ===== BÚSQUEDA =====
    'search_placeholder': 'Buscar productos, marcas y más...',
    'search': 'Buscar',
    'voice_search': 'Búsqueda por voz',
    'voice_search_not_supported': 'Tu navegador no soporta búsqueda por voz',
    'suggestions': 'Sugerencias',
    'recent_searches': 'Búsquedas recientes',
    'popular_searches': 'Búsquedas populares',
    'clear_recent': 'Limpiar búsquedas',
    'search_results_for': 'Resultados de búsqueda para',
    'products_found': 'productos encontrados',
    'filters': 'Filtros',
    'sort_by': 'Ordenar por',
    'relevance': 'Relevancia',
    'price_low_to_high': 'Precio: menor a mayor',
    'price_high_to_low': 'Precio: mayor a menor',
    'name_a_to_z': 'Nombre: A a Z',
    'category': 'Categoría',
    'all_categories': 'Todas las categorías',
    'price_range': 'Rango de precio',
    'in_stock_only': 'Solo en stock',
    'clear_filters': 'Limpiar filtros',
    'no_results': 'No encontramos resultados',
    'try_different_keywords': 'Prueba con diferentes palabras clave',
    'browse_all_products': 'Ver todos los productos',
    'searching': 'Buscando',
    
    // ===== PRODUCTOS =====
    'productos': 'Productos',
    'producto': 'Producto',
    'precio': 'Precio',
    'desde': 'Desde',
    'hasta': 'Hasta',
    'stock': 'Stock',
    'disponible': 'Disponible',
    'no_disponible': 'No disponible',
    'add_to_cart': 'Agregar al carrito',
    'out_of_stock': 'Sin stock',
    'quantity': 'Cantidad',
    'total': 'Total',
    'subtotal': 'Subtotal',
    'continue_shopping': 'Seguir comprando',
    'checkout': 'Finalizar compra',
    'vaciar_carrito': 'Vaciar carrito',
    'carrito_vacio': 'Tu carrito está vacío',
    'ir_comprar': 'Ir a comprar',
    'ver_todos': 'Ver todos',
    'comprar_ahora': 'Comprar ahora',
    
    // ===== SERVICIOS =====
    'servicios_turisticos': 'Servicios Turísticos',
    'descripcion_servicios': 'Descubre todos los servicios que tenemos para ti',
    'paqueteria_express': 'Paquetería Express',
    'envios_internacionales': 'Envíos internacionales',
    'paquetes_turisticos': 'Paquetes Turísticos',
    'viajes_incluido': 'Viajes todo incluido',
    'renta_autos': 'Renta de Autos',
    'vehiculos_lujo': 'Vehículos de lujo',
    'reservas_hoteles': 'Reservas de Hoteles',
    'mejores_tarifas': 'Mejores tarifas',
    'reservas_vuelos': 'Reservas de Vuelos',
    'aerolineas_internacionales': 'Aerolíneas internacionales',
    'visas': 'Visas',
    'tramite_profesional': 'Trámite profesional',
    'ver_detalles': 'Ver detalles',
    'destacado': 'Destacado',
    'ofertas': 'Ofertas',
    'mas_informacion': 'Más información',
    'proximamente': 'Próximamente',
    'preparando_servicios': 'Estamos preparando servicios increíbles para ti',
    
    // ===== PERFIL =====
    'bienvenido': 'Bienvenido',
    'cliente': 'Cliente',
    'administrador': 'Administrador',
    'mis_pedidos': 'Mis Pedidos',
    'mis_favoritos': 'Mis Favoritos',
    'mis_direcciones': 'Mis Direcciones',
    'configuracion': 'Configuración',
    'resumen': 'Resumen',
    'pedidos': 'Pedidos',
    'favoritos': 'Favoritos',
    'direcciones': 'Direcciones',
    'informacion_personal': 'Información Personal',
    'nombre_completo': 'Nombre completo',
    'correo_electronico': 'Correo electrónico',
    'telefono': 'Teléfono',
    'fecha_registro': 'Fecha de registro',
    'miembro_desde': 'Miembro desde',
    'guardar_cambios': 'Guardar cambios',
    'editar_perfil': 'Editar perfil',
    'cambiar_contraseña': 'Cambiar contraseña',
    'nueva_contraseña': 'Nueva contraseña',
    'confirmar_contraseña': 'Confirmar contraseña',
    'pedidos_realizados': 'Pedidos realizados',
    'productos_favoritos': 'Productos favoritos',
    'dias_como_miembro': 'Días como miembro',
    'puntos_acumulados': 'Puntos acumulados',
    'direcciones_guardadas': 'Direcciones guardadas',
    'agregar_direccion': 'Agregar dirección',
    'pais': 'País',
    'ciudad': 'Ciudad',
    'direccion': 'Dirección',
    'codigo_postal': 'Código postal',
    'telefono_contacto': 'Teléfono de contacto',
    'no_sesion': 'No has iniciado sesión',
    'sin_pedidos': 'No tienes pedidos aún',
    'sin_favoritos': 'No tienes favoritos aún',
    'sin_direcciones': 'No tienes direcciones guardadas',
    'id_pedido': 'ID Pedido',
    'fecha': 'Fecha',
    'estado': 'Estado',
    'entregado': 'Entregado',
    'en_camino': 'En camino',
    'procesando_pedido': 'Procesando pedido',
    'pedidos_recientes': 'Pedidos Recientes',
    'ir_tienda': 'Ir a Tienda',
    
    // ===== AUTENTICACIÓN =====
    'iniciar_sesion': 'Iniciar Sesión',
    'crear_cuenta': 'Crear Cuenta',
    'registrarme': 'Registrarme',
    'email': 'Correo electrónico',
    'contraseña': 'Contraseña',
    'recordarme': 'Recordarme',
    'olvide_contraseña': '¿Olvidaste tu contraseña?',
    'no_tienes_cuenta': '¿No tienes cuenta?',
    'ya_tienes_cuenta': '¿Ya tienes cuenta?',
    'registrate': 'Regístrate',
    'inicia_sesion': 'Inicia sesión',
    'continuar_invitado': 'Continuar como invitado',
    'bienvenido_usuario': '¡Bienvenido',
    'accede_continuar': 'Accede a tu cuenta para continuar',
    'registrate_comprar': 'Regístrate para comenzar a comprar',
    'tu_nombre': 'Tu nombre',
    'passwords_no_match': 'Las contraseñas no coinciden',
    
    // ===== FOOTER =====
    'contactanos': 'Contáctanos',
    'llamanos_ahora': 'LLÁMANOS AHORA',
    'escribenos': 'ESCRÍBENOS',
    'visitanos': 'VISÍTANOS',
    'horarios': 'Horarios',
    'lun_vie': 'Lunes a Viernes',
    'sabado': 'Sábado',
    'domingo': 'Domingo',
    'redes_sociales': 'Redes Sociales',
    'siguenos': 'Síguenos',
    'terminos_condiciones': 'Términos y condiciones',
    'politica_privacidad': 'Política de privacidad',
    'derechos': 'Todos los derechos reservados',
    'enlaces_rapidos': 'Enlaces rápidos',
    'copyright': '© {year} Batista Global Service. {rights}',
    
    // ===== ADMIN =====
    'panel_administrativo': 'Panel Administrativo',
    'dashboard': 'Dashboard',
    'gestion_productos': 'Gestión de Productos',
    'gestion_servicios': 'Gestión de Servicios',
    'gestion_pedidos': 'Gestión de Pedidos',
    'gestion_usuarios': 'Gestión de Usuarios',
    'analiticas': 'Analíticas',
    'configuracion_admin': 'Configuración',
    'nuevo_producto': 'Nuevo Producto',
    'nuevo_servicio': 'Nuevo Servicio',
    'editar': 'Editar',
    'eliminar': 'Eliminar',
    'activar': 'Activar',
    'desactivar': 'Desactivar',
    'buscar_admin': 'Buscar...',
    'todos': 'Todos',
    'aplicar': 'Aplicar',
    'exportar': 'Exportar',
    'importar': 'Importar',
    
    // ===== ERRORES =====
    'error_inesperado': 'Error inesperado',
    'intentar_nuevamente': 'Intentar nuevamente',
    'pagina_no_encontrada': 'Página no encontrada',
    'acceso_denegado': 'Acceso denegado',
    'no_autorizado': 'No autorizado',
    'sesion_expirada': 'Sesión expirada',
    'campos_obligatorios': 'Campos obligatorios',
    'formato_invalido': 'Formato inválido',
    
    // ===== TIEMPO =====
    'hoy': 'Hoy',
    'ayer': 'Ayer',
    'manana': 'Mañana',
    'dias': 'días',
    'semanas': 'semanas',
    'meses': 'meses',
    'años': 'años',
    'minutos': 'minutos',
    'horas': 'horas',
    
    // ===== MONEDA =====
    'usd': 'USD',
    'eur': 'EUR',
    'dop': 'DOP',
    'pesos': 'pesos',
    'dolares': 'dólares',
    
    // ===== UNIDADES =====
    'kg': 'kg',
    'lb': 'lb',
    'g': 'g',
    'unidad': 'unidad',
    'unidades': 'unidades',
    'paquete': 'paquete',
    'paquetes': 'paquetes'
  },
  en: {
    // ===== GENERAL =====
    'inicio': 'Home',
    'tienda': 'Store',
    'servicios': 'Services',
    'carrito': 'Cart',
    'perfil': 'Profile',
    'buscar': 'Search',
    'ingresar': 'Login',
    'cerrar_sesion': 'Logout',
    'mi_cuenta': 'My Account',
    'admin': 'Admin',
    'panel_admin': 'Admin Panel',
    'volver': 'Back',
    'atras': 'Back',
    'cancelar': 'Cancel',
    'guardar': 'Save',
    'aceptar': 'Accept',
    'cargando': 'Loading...',
    'error': 'Error',
    'exito': 'Success',
    'volver_inicio': 'Back to home',
    'procesando_general': 'Processing...',
    'confirmar_eliminacion': 'Are you sure you want to delete this item?',
    'cambios_guardados': 'Changes saved successfully',
    'sin_datos': 'No data to display',
    
    // ===== HEADER =====
    'buscar_productos': 'Search products, brands and more...',
    'explorar_tienda': 'Explore Store',
    'nuestros_servicios': 'Our Services',
    
    // ===== SEARCH =====
    'search_placeholder': 'Search products, brands and more...',
    'search': 'Search',
    'voice_search': 'Voice search',
    'voice_search_not_supported': 'Your browser does not support voice search',
    'suggestions': 'Suggestions',
    'recent_searches': 'Recent searches',
    'popular_searches': 'Popular searches',
    'clear_recent': 'Clear recent',
    'search_results_for': 'Search results for',
    'products_found': 'products found',
    'filters': 'Filters',
    'sort_by': 'Sort by',
    'relevance': 'Relevance',
    'price_low_to_high': 'Price: low to high',
    'price_high_to_low': 'Price: high to low',
    'name_a_to_z': 'Name: A to Z',
    'category': 'Category',
    'all_categories': 'All categories',
    'price_range': 'Price range',
    'in_stock_only': 'In stock only',
    'clear_filters': 'Clear filters',
    'no_results': 'No results found',
    'try_different_keywords': 'Try different keywords',
    'browse_all_products': 'Browse all products',
    'searching': 'Searching',
    
    // ===== PRODUCTS =====
    'productos': 'Products',
    'producto': 'Product',
    'precio': 'Price',
    'desde': 'From',
    'hasta': 'To',
    'stock': 'Stock',
    'disponible': 'Available',
    'no_disponible': 'Not available',
    'add_to_cart': 'Add to cart',
    'out_of_stock': 'Out of stock',
    'quantity': 'Quantity',
    'total': 'Total',
    'subtotal': 'Subtotal',
    'continue_shopping': 'Continue shopping',
    'checkout': 'Checkout',
    'vaciar_carrito': 'Empty cart',
    'carrito_vacio': 'Your cart is empty',
    'ir_comprar': 'Go shopping',
    'ver_todos': 'View all',
    'comprar_ahora': 'Buy now',
    
    // ===== SERVICES =====
    'servicios_turisticos': 'Tourist Services',
    'descripcion_servicios': 'Discover all the services we have for you',
    'paqueteria_express': 'Express Shipping',
    'envios_internacionales': 'International shipping',
    'paquetes_turisticos': 'Tour Packages',
    'viajes_incluido': 'All-inclusive trips',
    'renta_autos': 'Car Rental',
    'vehiculos_lujo': 'Luxury vehicles',
    'reservas_hoteles': 'Hotel Reservations',
    'mejores_tarifas': 'Best rates',
    'reservas_vuelos': 'Flight Reservations',
    'aerolineas_internacionales': 'International airlines',
    'visas': 'Visas',
    'tramite_profesional': 'Professional processing',
    'ver_detalles': 'View details',
    'destacado': 'Featured',
    'ofertas': 'Offers',
    'mas_informacion': 'More information',
    'proximamente': 'Coming soon',
    'preparando_servicios': 'We are preparing amazing services for you',
    
    // ===== PROFILE =====
    'bienvenido': 'Welcome',
    'cliente': 'Client',
    'administrador': 'Administrator',
    'mis_pedidos': 'My Orders',
    'mis_favoritos': 'My Favorites',
    'mis_direcciones': 'My Addresses',
    'configuracion': 'Settings',
    'resumen': 'Summary',
    'pedidos': 'Orders',
    'favoritos': 'Favorites',
    'direcciones': 'Addresses',
    'informacion_personal': 'Personal Information',
    'nombre_completo': 'Full name',
    'correo_electronico': 'Email',
    'telefono': 'Phone',
    'fecha_registro': 'Registration date',
    'miembro_desde': 'Member since',
    'guardar_cambios': 'Save changes',
    'editar_perfil': 'Edit profile',
    'cambiar_contraseña': 'Change password',
    'nueva_contraseña': 'New password',
    'confirmar_contraseña': 'Confirm password',
    'pedidos_realizados': 'Orders placed',
    'productos_favoritos': 'Favorite products',
    'dias_como_miembro': 'Days as member',
    'puntos_acumulados': 'Accumulated points',
    'direcciones_guardadas': 'Saved addresses',
    'agregar_direccion': 'Add address',
    'pais': 'Country',
    'ciudad': 'City',
    'direccion': 'Address',
    'codigo_postal': 'Postal code',
    'telefono_contacto': 'Contact phone',
    'no_sesion': 'You are not logged in',
    'sin_pedidos': 'You have no orders yet',
    'sin_favoritos': 'You have no favorites yet',
    'sin_direcciones': 'You have no saved addresses',
    'id_pedido': 'Order ID',
    'fecha': 'Date',
    'estado': 'Status',
    'entregado': 'Delivered',
    'en_camino': 'In transit',
    'procesando_pedido': 'Processing order',
    'pedidos_recientes': 'Recent Orders',
    'ir_tienda': 'Go to Store',
    
    // ===== AUTHENTICATION =====
    'iniciar_sesion': 'Sign In',
    'crear_cuenta': 'Create Account',
    'registrarme': 'Sign Up',
    'email': 'Email',
    'contraseña': 'Password',
    'recordarme': 'Remember me',
    'olvide_contraseña': 'Forgot password?',
    'no_tienes_cuenta': "Don't have an account?",
    'ya_tienes_cuenta': 'Already have an account?',
    'registrate': 'Sign up',
    'inicia_sesion': 'Sign in',
    'continuar_invitado': 'Continue as guest',
    'bienvenido_usuario': 'Welcome',
    'accede_continuar': 'Access your account to continue',
    'registrate_comprar': 'Sign up to start shopping',
    'tu_nombre': 'Your name',
    'passwords_no_match': 'Passwords do not match',
    
    // ===== FOOTER =====
    'contactanos': 'Contact us',
    'llamanos_ahora': 'CALL US NOW',
    'escribenos': 'WRITE TO US',
    'visitanos': 'VISIT US',
    'horarios': 'Hours',
    'lun_vie': 'Monday to Friday',
    'sabado': 'Saturday',
    'domingo': 'Sunday',
    'redes_sociales': 'Social Media',
    'siguenos': 'Follow us',
    'terminos_condiciones': 'Terms and conditions',
    'politica_privacidad': 'Privacy policy',
    'derechos': 'All rights reserved',
    'enlaces_rapidos': 'Quick links',
    'copyright': '© {year} Batista Global Service. {rights}',
    
    // ===== ADMIN =====
    'panel_administrativo': 'Administrative Panel',
    'dashboard': 'Dashboard',
    'gestion_productos': 'Product Management',
    'gestion_servicios': 'Service Management',
    'gestion_pedidos': 'Order Management',
    'gestion_usuarios': 'User Management',
    'analiticas': 'Analytics',
    'configuracion_admin': 'Settings',
    'nuevo_producto': 'New Product',
    'nuevo_servicio': 'New Service',
    'editar': 'Edit',
    'eliminar': 'Delete',
    'activar': 'Activate',
    'desactivar': 'Deactivate',
    'buscar_admin': 'Search...',
    'todos': 'All',
    'aplicar': 'Apply',
    'exportar': 'Export',
    'importar': 'Import',
    
    // ===== ERRORS =====
    'error_inesperado': 'Unexpected error',
    'intentar_nuevamente': 'Try again',
    'pagina_no_encontrada': 'Page not found',
    'acceso_denegado': 'Access denied',
    'no_autorizado': 'Unauthorized',
    'sesion_expirada': 'Session expired',
    'campos_obligatorios': 'Required fields',
    'formato_invalido': 'Invalid format',
    
    // ===== TIME =====
    'hoy': 'Today',
    'ayer': 'Yesterday',
    'manana': 'Tomorrow',
    'dias': 'days',
    'semanas': 'weeks',
    'meses': 'months',
    'años': 'years',
    'minutos': 'minutes',
    'horas': 'hours',
    
    // ===== CURRENCY =====
    'usd': 'USD',
    'eur': 'EUR',
    'dop': 'DOP',
    'pesos': 'pesos',
    'dolares': 'dollars',
    
    // ===== UNITS =====
    'kg': 'kg',
    'lb': 'lb',
    'g': 'g',
    'unidad': 'unit',
    'unidades': 'units',
    'paquete': 'package',
    'paquetes': 'packages'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'es';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key, params = {}) => {
    let text = translations[language]?.[key] || translations.es[key] || key;
    
    Object.keys(params).forEach(param => {
      text = text.replace(`{${param}}`, params[param]);
    });
    
    return text;
  };

  const value = {
    language,
    setLanguage,
    t,
    translations: translations[language]
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
